### PR TITLE
Implementing Generalized linear mixed models

### PR DESCRIPTION
**Pull request by MaikH88**
I have added the variable "model" to the function linmixmod, which allows to perfom either a linear mixed model (model=0) or a generalized linear mixed model (GLMM) with a log-link function (model=1). GLMM might be better suited for skewed distributions like deformation. The user should be able to decide which model should be applied. Therefore I suggest a dropdown menu for LMM and GLMM

### CODE REVIEW

**Comment by paulmueller** [comment]
Thanks for the pull request. The checks fail. I think it is because of the new argument `model` which should be a keyword argument. Instead of the possible values "0" and "1", I would prefer "linear" and "generalized" or some such kind.

**Comment by MaikH88** [comment]
very goof idea. I changed it to 'glmm' and 'lmm'

**Comment by paulmueller** [comment]
The tests still fail... Please make sure to set 'lmm' as default

**Comment by MaikH88** [comment]
I have added 'lmm' as default argument, but the tests still fail. On my machine this script runs coorectly and without any error. Paul, do you have an idea what could be the problem?

**Comment by paulmueller** [comment]
It's a coveralls issue. The tests pass.

**Comment by katpla** [comment]
Hi,
what is the status of this one? there seems to be no artifacts in this release

**Comment by paulmueller** [comment]
There are no artifacts, because Maiks branch is not allowed to submit to coveralls (I will fix this in the future). Either way, you would not benefit from a build, because the user interface needs to be updated to allow generalized lmm.

**Comment by paulmueller** [comment]
I am merging this into a separate branch for testing.

**Comment by paulmueller** [comment]
I am not merging into develop yes. Further discussions in issue #126.

**Pull request merged**
